### ISSUE TITLE
Tracking lexical order of entries in an Object

### ISSUE THREAD

**Issue by endgame** [haskell/aeson#984] opened 2022-12-09 05:45 UTC
The [`amazonka`](https://github.com/brendanhay/amazonka) generator parses JSON files provided by AWS, which describe (among other things) the shape of request/response structures.

Example, from the S3 definition: https://github.com/boto/botocore/blob/ddea582093c5430fda84ff886629752e96ba9e35/botocore/data/s3/2006-03-01/service-2.json#L4517-L4732

For the generator, it would be nice to generate structs whose fields match the order of keys in the file, but by the time we get to `parseJSON` an `Object` is already a `KeyMap Value` and that information is lost. [`jsonWith`](https://hackage.haskell.org/package/aeson-2.1.1.0/docs/Data-Aeson-Parser.html#v:jsonWith) looks promising, but I think I can't use it because the callback must return an `Either String Object`. Am I missing something here?

**Comment by phadej** [comment] 2022-12-09 16:24
Duplicate of #368. Nothing have changed since.

This is known deficiency but most proposed solutions are not worth it. #560 based parsing is promising, but requires a lot of time to work out, without sponsoring it's unlikely I'll work on it.

**Closed by phadej** 2022-12-09 16:24 UTC

**Comment by endgame** [comment] 2022-12-11 23:02
Thanks for the link to the dupe, I'll go `+1` it so we have some visibility on whether this is a widely-wanted feature or a niche one.
